country_data =
    {"australia": {"name": "Australia"},
     "france": {"name": "France"},
     "united states": {"name": "USA"},
     "canada": {"name": "Canada"},
     "iran": {"name": "Iran"},
     "saudi arabia": {"name": "Saudi Arabia"},
     "germany": {"name": "Germany"},
     "finland": {"name": "Finland"},
     "netherlands": {"name": "Netherlands"},
     "italy": {"name": "Italy"},
     "hungary": {"name": "Hungary"},
     "bulgaria": {"name": "Bulgaria"},
     "russia": {"name": "Russia"},
     "poland": {"name": "Poland"},
     "united kingdom": {"name": "United Kingdom"},
     "turkey": {"name": "Turkey"},
     "china": {"name": "China"},
     "indonesia": {"name": "Indonesia"},
     "vietnam": {"name": "Vietnam"},
     "middle south america": {"name": "Middle/South America"}};
